/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppClientsIndexRouteImport } from './routes/app/clients/index'
import { Route as AppClientsIdRouteImport } from './routes/app/clients/$id'
import { Route as AppClientsNewRouteImport } from './routes/app/clients/new'
import { Route as AppInvoicesIndexRouteImport } from './routes/app/invoices/index'
import { Route as AppInvoicesIdRouteImport } from './routes/app/invoices/$id'
import { Route as AppInvoicesCreateRouteImport } from './routes/app/invoices/create'
import { Route as AppProjectsIndexRouteImport } from './routes/app/projects/index'
import { Route as AppProjectsIdRouteImport } from './routes/app/projects/$id'
import { Route as AppReportsIndexRouteImport } from './routes/app/reports/index'
import { Route as AppSettingsAccountRouteImport } from './routes/app/settings/account'
import { Route as AppSettingsWorkspaceRouteImport } from './routes/app/settings/workspace'
import { Route as AppWorkspacesIndexRouteImport } from './routes/app/workspaces/index'
import { Route as AppWorkspacesIdRouteImport } from './routes/app/workspaces/$id'
import { Route as AppReportsSavedIndexRouteImport } from './routes/app/reports/saved/index'
import { Route as AppReportsSavedIdRouteImport } from './routes/app/reports/saved/$id'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClientsIdRoute = AppClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClientsNewRoute = AppClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInvoicesIdRoute = AppInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInvoicesCreateRoute = AppInvoicesCreateRouteImport.update({
  id: '/invoices/create',
  path: '/invoices/create',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsWorkspaceRoute = AppSettingsWorkspaceRouteImport.update({
  id: '/settings/workspace',
  path: '/settings/workspace',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkspacesIndexRoute = AppWorkspacesIndexRouteImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkspacesIdRoute = AppWorkspacesIdRouteImport.update({
  id: '/workspaces/$id',
  path: '/workspaces/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportsSavedIndexRoute = AppReportsSavedIndexRouteImport.update({
  id: '/reports/saved/',
  path: '/reports/saved/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportsSavedIdRoute = AppReportsSavedIdRouteImport.update({
  id: '/reports/saved/$id',
  path: '/reports/saved/$id',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/app/': typeof AppIndexRoute
  '/app/clients/$id': typeof AppClientsIdRoute
  '/app/clients/new': typeof AppClientsNewRoute
  '/app/invoices/$id': typeof AppInvoicesIdRoute
  '/app/invoices/create': typeof AppInvoicesCreateRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
  '/app/settings/account': typeof AppSettingsAccountRoute
  '/app/settings/workspace': typeof AppSettingsWorkspaceRoute
  '/app/workspaces/$id': typeof AppWorkspacesIdRoute
  '/app/clients/': typeof AppClientsIndexRoute
  '/app/invoices/': typeof AppInvoicesIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/app/reports/': typeof AppReportsIndexRoute
  '/app/workspaces/': typeof AppWorkspacesIndexRoute
  '/app/reports/saved/$id': typeof AppReportsSavedIdRoute
  '/app/reports/saved/': typeof AppReportsSavedIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/': typeof PublicIndexRoute
  '/app': typeof AppIndexRoute
  '/app/clients/$id': typeof AppClientsIdRoute
  '/app/clients/new': typeof AppClientsNewRoute
  '/app/invoices/$id': typeof AppInvoicesIdRoute
  '/app/invoices/create': typeof AppInvoicesCreateRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
  '/app/settings/account': typeof AppSettingsAccountRoute
  '/app/settings/workspace': typeof AppSettingsWorkspaceRoute
  '/app/workspaces/$id': typeof AppWorkspacesIdRoute
  '/app/clients': typeof AppClientsIndexRoute
  '/app/invoices': typeof AppInvoicesIndexRoute
  '/app/projects': typeof AppProjectsIndexRoute
  '/app/reports': typeof AppReportsIndexRoute
  '/app/workspaces': typeof AppWorkspacesIndexRoute
  '/app/reports/saved/$id': typeof AppReportsSavedIdRoute
  '/app/reports/saved': typeof AppReportsSavedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_public/': typeof PublicIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/clients/$id': typeof AppClientsIdRoute
  '/app/clients/new': typeof AppClientsNewRoute
  '/app/invoices/$id': typeof AppInvoicesIdRoute
  '/app/invoices/create': typeof AppInvoicesCreateRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
  '/app/settings/account': typeof AppSettingsAccountRoute
  '/app/settings/workspace': typeof AppSettingsWorkspaceRoute
  '/app/workspaces/$id': typeof AppWorkspacesIdRoute
  '/app/clients/': typeof AppClientsIndexRoute
  '/app/invoices/': typeof AppInvoicesIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/app/reports/': typeof AppReportsIndexRoute
  '/app/workspaces/': typeof AppWorkspacesIndexRoute
  '/app/reports/saved/$id': typeof AppReportsSavedIdRoute
  '/app/reports/saved/': typeof AppReportsSavedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/'
    | '/app/clients/$id'
    | '/app/clients/new'
    | '/app/invoices/$id'
    | '/app/invoices/create'
    | '/app/projects/$id'
    | '/app/settings/account'
    | '/app/settings/workspace'
    | '/app/workspaces/$id'
    | '/app/clients/'
    | '/app/invoices/'
    | '/app/projects/'
    | '/app/reports/'
    | '/app/workspaces/'
    | '/app/reports/saved/$id'
    | '/app/reports/saved/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/'
    | '/app'
    | '/app/clients/$id'
    | '/app/clients/new'
    | '/app/invoices/$id'
    | '/app/invoices/create'
    | '/app/projects/$id'
    | '/app/settings/account'
    | '/app/settings/workspace'
    | '/app/workspaces/$id'
    | '/app/clients'
    | '/app/invoices'
    | '/app/projects'
    | '/app/reports'
    | '/app/workspaces'
    | '/app/reports/saved/$id'
    | '/app/reports/saved'
  id:
    | '__root__'
    | '/_public'
    | '/app'
    | '/_public/login'
    | '/_public/register'
    | '/_public/'
    | '/app/'
    | '/app/clients/$id'
    | '/app/clients/new'
    | '/app/invoices/$id'
    | '/app/invoices/create'
    | '/app/projects/$id'
    | '/app/settings/account'
    | '/app/settings/workspace'
    | '/app/workspaces/$id'
    | '/app/clients/'
    | '/app/invoices/'
    | '/app/projects/'
    | '/app/reports/'
    | '/app/workspaces/'
    | '/app/reports/saved/$id'
    | '/app/reports/saved/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/clients/': {
      id: '/app/clients/'
      path: '/clients'
      fullPath: '/app/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/clients/$id': {
      id: '/app/clients/$id'
      path: '/clients/$id'
      fullPath: '/app/clients/$id'
      preLoaderRoute: typeof AppClientsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/clients/new': {
      id: '/app/clients/new'
      path: '/clients/new'
      fullPath: '/app/clients/new'
      preLoaderRoute: typeof AppClientsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/invoices/': {
      id: '/app/invoices/'
      path: '/invoices'
      fullPath: '/app/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/invoices/$id': {
      id: '/app/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/app/invoices/$id'
      preLoaderRoute: typeof AppInvoicesIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/invoices/create': {
      id: '/app/invoices/create'
      path: '/invoices/create'
      fullPath: '/app/invoices/create'
      preLoaderRoute: typeof AppInvoicesCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/projects/': {
      id: '/app/projects/'
      path: '/projects'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/projects/$id': {
      id: '/app/projects/$id'
      path: '/projects/$id'
      fullPath: '/app/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/reports/': {
      id: '/app/reports/'
      path: '/reports'
      fullPath: '/app/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/account': {
      id: '/app/settings/account'
      path: '/settings/account'
      fullPath: '/app/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/workspace': {
      id: '/app/settings/workspace'
      path: '/settings/workspace'
      fullPath: '/app/settings/workspace'
      preLoaderRoute: typeof AppSettingsWorkspaceRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/workspaces/': {
      id: '/app/workspaces/'
      path: '/workspaces'
      fullPath: '/app/workspaces/'
      preLoaderRoute: typeof AppWorkspacesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/workspaces/$id': {
      id: '/app/workspaces/$id'
      path: '/workspaces/$id'
      fullPath: '/app/workspaces/$id'
      preLoaderRoute: typeof AppWorkspacesIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/reports/saved/': {
      id: '/app/reports/saved/'
      path: '/reports/saved'
      fullPath: '/app/reports/saved/'
      preLoaderRoute: typeof AppReportsSavedIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/reports/saved/$id': {
      id: '/app/reports/saved/$id'
      path: '/reports/saved/$id'
      fullPath: '/app/reports/saved/$id'
      preLoaderRoute: typeof AppReportsSavedIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppClientsIdRoute: typeof AppClientsIdRoute
  AppClientsNewRoute: typeof AppClientsNewRoute
  AppInvoicesIdRoute: typeof AppInvoicesIdRoute
  AppInvoicesCreateRoute: typeof AppInvoicesCreateRoute
  AppProjectsIdRoute: typeof AppProjectsIdRoute
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsWorkspaceRoute: typeof AppSettingsWorkspaceRoute
  AppWorkspacesIdRoute: typeof AppWorkspacesIdRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppWorkspacesIndexRoute: typeof AppWorkspacesIndexRoute
  AppReportsSavedIdRoute: typeof AppReportsSavedIdRoute
  AppReportsSavedIndexRoute: typeof AppReportsSavedIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppClientsIdRoute: AppClientsIdRoute,
  AppClientsNewRoute: AppClientsNewRoute,
  AppInvoicesIdRoute: AppInvoicesIdRoute,
  AppInvoicesCreateRoute: AppInvoicesCreateRoute,
  AppProjectsIdRoute: AppProjectsIdRoute,
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsWorkspaceRoute: AppSettingsWorkspaceRoute,
  AppWorkspacesIdRoute: AppWorkspacesIdRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppWorkspacesIndexRoute: AppWorkspacesIndexRoute,
  AppReportsSavedIdRoute: AppReportsSavedIdRoute,
  AppReportsSavedIndexRoute: AppReportsSavedIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
