/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live Check */
        get: operations["live_check_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Db Stat */
        get: operations["db_stat_api_v1_health_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/new": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_new_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Logout */
        delete: operations["logout_api_v1_auth_logout_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/justice-search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Client Company */
        get: operations["search_client_company_api_v1_clients_justice_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Clients */
        get: operations["get_clients_api_v1_clients__get"];
        put?: never;
        /** Create Client */
        post: operations["create_client_api_v1_clients__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Client */
        get: operations["get_client_api_v1_clients__id__get"];
        /** Update Client */
        put: operations["update_client_api_v1_clients__id__put"];
        post?: never;
        /** Delete Client */
        delete: operations["delete_client_api_v1_clients__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Projects */
        get: operations["get_projects_api_v1_projects__get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_v1_projects__post"];
        /** Bulk Delete */
        delete: operations["bulk_delete_api_v1_projects__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_v1_projects__id__get"];
        /** Update Project */
        put: operations["update_project_api_v1_projects__id__put"];
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_api_v1_projects__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/time-entries/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Time Entries */
        get: operations["get_all_time_entries_api_v1_time_entries__get"];
        put?: never;
        /** Create Time Entry */
        post: operations["create_time_entry_api_v1_time_entries__post"];
        /** Bulk Delete */
        delete: operations["bulk_delete_api_v1_time_entries__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/time-entries/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Calendar Entries */
        get: operations["get_calendar_entries_api_v1_time_entries_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/time-entries/last": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Last Entry */
        get: operations["get_last_entry_api_v1_time_entries_last_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/time-entries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Time Entry */
        get: operations["get_time_entry_api_v1_time_entries__id__get"];
        /** Update Time Entry */
        put: operations["update_time_entry_api_v1_time_entries__id__put"];
        post?: never;
        /** Delete Time Entry */
        delete: operations["delete_time_entry_api_v1_time_entries__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workspaces */
        get: operations["list_workspaces_api_v1_workspaces_get"];
        put?: never;
        /** Create Workspace */
        post: operations["create_workspace_api_v1_workspaces_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Workspace */
        delete: operations["delete_workspace_api_v1_workspaces__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Workspace Members
         * @description Get all members for selected workspace
         */
        get: operations["list_workspace_members_api_v1_workspaces_members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/members/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Workspace Member
         * @description Update workspace member
         */
        put: operations["update_workspace_member_api_v1_workspaces_members__member_id__put"];
        post?: never;
        /**
         * Remove Workspace Member
         * @description removes member from workspace
         */
        delete: operations["remove_workspace_member_api_v1_workspaces_members__member_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/members/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Leave Workspace
         * @description removes requestee from workspace
         */
        delete: operations["leave_workspace_api_v1_workspaces_members_me_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All Workspace Invitations */
        get: operations["list_all_workspace_invitations_api_v1_workspaces_invitations_get"];
        put?: never;
        /** Create Invitation */
        post: operations["create_invitation_api_v1_workspaces_invitations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/invitations/accept/{invitation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Invitation */
        post: operations["accept_invitation_api_v1_workspaces_invitations_accept__invitation_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/invitations/revoke/{invitation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Invitation */
        delete: operations["revoke_invitation_api_v1_workspaces_invitations_revoke__invitation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Live Report */
        get: operations["get_live_report_api_v1_reports_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Static Reports */
        get: operations["get_static_reports_api_v1_reports__get"];
        put?: never;
        /** Save Live Report */
        post: operations["save_live_report_api_v1_reports__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Single Static Report */
        get: operations["get_single_static_report_api_v1_reports__id__get"];
        put?: never;
        post?: never;
        /** Delete Static Report */
        delete: operations["delete_static_report_api_v1_reports__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{id}/share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Share Static Report */
        put: operations["share_static_report_api_v1_reports__id__share_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Notifications */
        get: operations["get_all_notifications_api_v1_notifications__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Read Notification */
        put: operations["read_notification_api_v1_notifications__id__read_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_login_api_v1_auth__post */
        Body_login_api_v1_auth__post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** ClientCreate */
        ClientCreate: {
            /** Name */
            name: string;
            /** Hourly Rate */
            hourly_rate?: number | string | null;
            /** Is Company */
            is_company?: boolean | null;
            /** Street */
            street?: string | null;
            /** City */
            city?: string | null;
            /** Postal Code */
            postal_code?: string | null;
            /** Country */
            country?: string | null;
            /** Ico */
            ico?: string | null;
            /** Dic */
            dic?: string | null;
            /**
             * Vat Payer
             * @default false
             */
            vat_payer: boolean | null;
            /** Bank Account */
            bank_account?: string | null;
            /** Iban */
            iban?: string | null;
            /** Currency */
            currency?: string | null;
            /** Discount Percentage */
            discount_percentage?: number | string | null;
        };
        /** ClientRead */
        ClientRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Hourly Rate */
            hourly_rate: string | null;
            /** Is Company */
            is_company: boolean | null;
            /** Street */
            street: string | null;
            /** City */
            city: string | null;
            /** Postal Code */
            postal_code: string | null;
            /** Country */
            country: string | null;
            /** Ico */
            ico: string | null;
            /** Dic */
            dic: string | null;
            /** Vat Payer */
            vat_payer: boolean | null;
            /** Bank Account */
            bank_account: string | null;
            /** Iban */
            iban: string | null;
            /** Currency */
            currency: string | null;
            /** Discount Percentage */
            discount_percentage: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ClientShallow */
        ClientShallow: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Hourly Rate */
            hourly_rate: string | null;
            /** Is Company */
            is_company: boolean | null;
            /** Street */
            street: string | null;
            /** City */
            city: string | null;
            /** Postal Code */
            postal_code: string | null;
            /** Country */
            country: string | null;
            /** Ico */
            ico: string | null;
            /** Dic */
            dic: string | null;
            /** Vat Payer */
            vat_payer: boolean | null;
            /** Bank Account */
            bank_account: string | null;
            /** Iban */
            iban: string | null;
            /** Currency */
            currency: string | null;
            /** Discount Percentage */
            discount_percentage: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ClientUpdate */
        ClientUpdate: {
            /** Name */
            name: string;
            /** Hourly Rate */
            hourly_rate?: number | string | null;
            /** Is Company */
            is_company?: boolean | null;
            /** Street */
            street?: string | null;
            /** City */
            city?: string | null;
            /** Postal Code */
            postal_code?: string | null;
            /** Country */
            country?: string | null;
            /** Ico */
            ico?: string | null;
            /** Dic */
            dic?: string | null;
            /**
             * Vat Payer
             * @default false
             */
            vat_payer: boolean | null;
            /** Bank Account */
            bank_account?: string | null;
            /** Iban */
            iban?: string | null;
            /** Currency */
            currency?: string | null;
            /** Discount Percentage */
            discount_percentage?: number | string | null;
        };
        /** CreateReport */
        CreateReport: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /**
             * Period Start
             * Format: date-time
             */
            period_start: string;
            /**
             * Period End
             * Format: date-time
             */
            period_end: string;
            /** Client Ids */
            client_ids?: number[] | null;
            /** Project Ids */
            project_ids?: number[] | null;
            /** Billable */
            billable?: boolean | null;
        };
        /** DbStat */
        DbStat: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "unavailable";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LiveCheck */
        LiveCheck: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** LoginResponse */
        LoginResponse: {
            user: components["schemas"]["UserRead"];
            token: components["schemas"]["Token"];
        };
        /** NotificationRead */
        NotificationRead: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            type: components["schemas"]["NotificationType"];
            /** Payload */
            payload: components["schemas"]["WorkspaceInvitePayload"] | components["schemas"]["WorkspaceInviteAcceptedPayload"] | components["schemas"]["WorkspaceRemovedPayload"] | components["schemas"]["WorkspaceRoleChangedPayload"] | components["schemas"]["WorkspaceLeftPayload"];
            /** Read At */
            read_at?: string | null;
        };
        /**
         * NotificationType
         * @enum {string}
         */
        NotificationType: "workspace_invite" | "workspace_invite_accepted" | "workspace_removed" | "workspace_role_changed" | "workspace_left";
        /** Page[ClientRead] */
        Page_ClientRead_: {
            /** Items */
            items: components["schemas"]["ClientRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** Page[NotificationRead] */
        Page_NotificationRead_: {
            /** Items */
            items: components["schemas"]["NotificationRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** Page[ProjectRead] */
        Page_ProjectRead_: {
            /** Items */
            items: components["schemas"]["ProjectRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** Page[ReportRead] */
        Page_ReportRead_: {
            /** Items */
            items: components["schemas"]["ReportRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** Page[TimeEntryRead] */
        Page_TimeEntryRead_: {
            /** Items */
            items: components["schemas"]["TimeEntryRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** Page[WorkspaceInvitationRead] */
        Page_WorkspaceInvitationRead_: {
            /** Items */
            items: components["schemas"]["WorkspaceInvitationRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** Page[WorkspaceMemberRead] */
        Page_WorkspaceMemberRead_: {
            /** Items */
            items: components["schemas"]["WorkspaceMemberRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** Page[WorkspaceRead] */
        Page_WorkspaceRead_: {
            /** Items */
            items: components["schemas"]["WorkspaceRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** ProjectBulkDelete */
        ProjectBulkDelete: {
            /** Ids */
            ids: number[];
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
        };
        /** ProjectRead */
        ProjectRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            client: components["schemas"]["ClientRead"] | null;
            /** Description */
            description: string | null;
            /** Start Time */
            start_time: string | null;
            /** End Time */
            end_time: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProjectShallow */
        ProjectShallow: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Start Time */
            start_time: string | null;
            /** End Time */
            end_time: string | null;
        };
        /** ProjectUpdate */
        ProjectUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
        };
        /** ReportClientSnapshot */
        ReportClientSnapshot: {
            /** Name */
            name: string;
            /** Hourly Rate */
            hourly_rate: string | null;
            /** Currency */
            currency: string;
        };
        /** ReportEntrySnapshot */
        ReportEntrySnapshot: {
            /** Id */
            id: number;
            /** Report Id */
            report_id: number;
            /** Time Entry Id */
            time_entry_id: number | null;
            /** Duration Minutes */
            duration_minutes: number;
            /** Description */
            description: string;
            /**
             * Logged At
             * Format: date-time
             */
            logged_at: string;
            /** Client Name */
            client_name: string | null;
            /** Project Name */
            project_name: string | null;
        };
        /** ReportProjectSnapshot */
        ReportProjectSnapshot: {
            /** Name */
            name: string;
        };
        /** ReportRead */
        ReportRead: {
            /** Id */
            id: number;
            /**
             * Period Start
             * Format: date-time
             */
            period_start: string;
            /**
             * Period End
             * Format: date-time
             */
            period_end: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Workspace Id */
            workspace_id: number;
            /** Client Snapshot */
            client_snapshot: components["schemas"]["ReportClientSnapshot"][];
            /** Project Snapshot */
            project_snapshot: components["schemas"]["ReportProjectSnapshot"][];
            /** Snapshots */
            snapshots: components["schemas"]["ReportEntrySnapshot"][];
        };
        /** TimeEntryBulkDelete */
        TimeEntryBulkDelete: {
            /** Ids */
            ids: number[];
        };
        /** TimeEntryCreate */
        TimeEntryCreate: {
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /** Description */
            description?: string | null;
            /** Project Id */
            project_id?: number | null;
            /** Client Id */
            client_id?: number | null;
            /**
             * Billable
             * @default false
             */
            billable: boolean | null;
        };
        /** TimeEntryRead */
        TimeEntryRead: {
            /** Id */
            id: number;
            /** Description */
            description: string | null;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /** End Time */
            end_time: string | null;
            /** Workspace Id */
            workspace_id: number;
            /** Client Id */
            client_id: number | null;
            /** Project Id */
            project_id: number | null;
            /** User Id */
            user_id: number;
            client: components["schemas"]["ClientRead"] | null;
            project: components["schemas"]["ProjectShallow"] | null;
            /** Billable */
            billable: boolean;
        };
        /** TimeEntrySummary */
        TimeEntrySummary: {
            /** Id */
            id: number;
            /** Description */
            description: string | null;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /** End Time */
            end_time: string | null;
            /** Workspace Id */
            workspace_id: number;
            project: components["schemas"]["ProjectShallow"] | null;
            /** Billable */
            billable: boolean;
        };
        /** TimeEntryUpdate */
        TimeEntryUpdate: {
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /** Description */
            description?: string | null;
            /** Project Id */
            project_id?: number | null;
            /** Client Id */
            client_id?: number | null;
            /**
             * Billable
             * @default false
             */
            billable: boolean | null;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /** Token Type */
            token_type: string;
        };
        /** UserCreate */
        UserCreate: {
            /** Email */
            email: string;
            /**
             * Country
             * @default CZ
             */
            country: string;
            /** Name */
            name: string;
            /** Password */
            password: string;
        };
        /** UserRead */
        UserRead: {
            /** Email */
            email: string;
            /** Country */
            country: string;
            /** Name */
            name: string;
            /** Id */
            id: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkspaceCreate */
        WorkspaceCreate: {
            /** Name */
            name: string;
        };
        /** WorkspaceInvitationCreate */
        WorkspaceInvitationCreate: {
            /** Email */
            email: string;
            role?: components["schemas"]["WorkspaceRole"] | null;
            /** Expires At */
            expires_at?: string | null;
        };
        /** WorkspaceInvitationRead */
        WorkspaceInvitationRead: {
            /** Id */
            id: number;
            /** Workspace Id */
            workspace_id: number;
            /** User Id */
            user_id: number;
            role: components["schemas"]["WorkspaceRole"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Expires At */
            expires_at: string | null;
            /** Accepted At */
            accepted_at: string | null;
            /** Revoked At */
            revoked_at: string | null;
        };
        /** WorkspaceInviteAcceptedPayload */
        WorkspaceInviteAcceptedPayload: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "workspace_invite_accepted";
            /** Workspace Id */
            workspace_id: number;
            /** Workspace Name */
            workspace_name: string;
            /** Accepted By User Id */
            accepted_by_user_id: number;
            /** Accepted By Name */
            accepted_by_name: string;
            /** Role */
            role: string;
        };
        /** WorkspaceInvitePayload */
        WorkspaceInvitePayload: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "workspace_invite";
            /** Invitation Id */
            invitation_id: number;
            /** Workspace Id */
            workspace_id: number;
            /** Workspace Name */
            workspace_name: string;
            /** Invited By User Id */
            invited_by_user_id: number;
            /** Invited By Name */
            invited_by_name: string;
            /** Role */
            role: string;
        };
        /** WorkspaceLeftPayload */
        WorkspaceLeftPayload: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "workspace_left";
            /** Workspace Id */
            workspace_id: number;
            /** Workspace Name */
            workspace_name: string;
            /** User Id */
            user_id: number;
            /** User Name */
            user_name: string;
        };
        /** WorkspaceMemberRead */
        WorkspaceMemberRead: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            user: components["schemas"]["UserRead"];
            role: components["schemas"]["WorkspaceRole"];
        };
        /** WorkspaceMemberUpdate */
        WorkspaceMemberUpdate: {
            role: components["schemas"]["WorkspaceRole"];
        };
        /** WorkspaceRead */
        WorkspaceRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Members */
            members: components["schemas"]["WorkspaceMemberRead"][];
            /** Clients */
            clients: components["schemas"]["ClientShallow"][];
            /** Time Entries */
            time_entries: components["schemas"]["TimeEntryRead"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** WorkspaceRemovedPayload */
        WorkspaceRemovedPayload: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "workspace_removed";
            /** Workspace Id */
            workspace_id: number;
            /** Workspace Name */
            workspace_name: string;
            /** Removed By User Id */
            removed_by_user_id: number;
            /** Removed By Name */
            removed_by_name: string;
        };
        /**
         * WorkspaceRole
         * @enum {string}
         */
        WorkspaceRole: "owner" | "admin" | "member";
        /** WorkspaceRoleChangedPayload */
        WorkspaceRoleChangedPayload: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "workspace_role_changed";
            /** Workspace Id */
            workspace_id: number;
            /** Workspace Name */
            workspace_name: string;
            /** Member User Id */
            member_user_id: number;
            /** Member Name */
            member_name: string;
            /** Changed By User Id */
            changed_by_user_id: number;
            /** Changed By Name */
            changed_by_name: string;
            /** Old Role */
            old_role: string;
            /** New Role */
            new_role: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live_check_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveCheck"];
                };
            };
        };
    };
    db_stat_api_v1_health_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DbStat"];
                };
            };
        };
    };
    login_api_v1_auth__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_auth__post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_v1_auth_new_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_client_company_api_v1_clients_justice_search_get: {
        parameters: {
            query: {
                query: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_clients_api_v1_clients__get: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Page size */
                size?: number;
            };
            header: {
                "X-Workspace-Id": number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ClientRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_client_api_v1_clients__post: {
        parameters: {
            query?: never;
            header: {
                "X-Workspace-Id": number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_client_api_v1_clients__id__get: {
        parameters: {
            query?: never;
            header: {
                "X-Workspace-Id": number;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_client_api_v1_clients__id__put: {
        parameters: {
            query?: never;
            header: {
                "X-Workspace-Id": number;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_client_api_v1_clients__id__delete: {
        parameters: {
            query?: never;
            header: {
                "X-Workspace-Id": number;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_projects_api_v1_projects__get: {
        parameters: {
            query?: {
                client_id?: number | null;
                /** @description Page number */
                page?: number;
                /** @description Page size */
                size?: number;
            };
            header: {
                "X-Workspace-Id": number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ProjectRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_v1_projects__post: {
        parameters: {
            query: {
                client_id: number;
            };
            header: {
                "X-Workspace-Id": number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_delete_api_v1_projects__delete: {
        parameters: {
            query: {
                client_id: number;
            };
            header: {
                "X-Workspace-Id": number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectBulkDelete"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_projects__id__get: {
        parameters: {
            query?: never;
            header: {
                "X-Workspace-Id": number;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_v1_projects__id__put: {
        parameters: {
            query: {
                client_id: number;
            };
            header: {
                "X-Workspace-Id": number;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_v1_projects__id__delete: {
        parameters: {
            query: {
                client_id: number;
            };
            header: {
                "X-Workspace-Id": number;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_time_entries_api_v1_time_entries__get: {
        parameters: {
            query?: {
                project_id?: number | null;
                start_time?: string | null;
                end_time?: string | null;
                billable?: boolean | null;
                /** @description Page number */
                page?: number;
                /** @description Page size */
                size?: number;
            };
            header: {
                "X-Workspace-Id": number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_TimeEntryRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_time_entry_api_v1_time_entries__post: {
        parameters: {
            query?: never;
            header: {
                "X-Workspace-Id": number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimeEntryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeEntryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_delete_api_v1_time_entries__delete: {
        parameters: {
            query?: never;
            header: {
                "X-Workspace-Id": number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimeEntryBulkDelete"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_calendar_entries_api_v1_time_entries_calendar_get: {
        parameters: {
            query: {
                start_time: string;
                end_time: string;
            };
            header: {
                "X-Workspace-Id": number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeEntrySummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_last_entry_api_v1_time_entries_last_get: {
        parameters: {
            query?: never;
            header: {
                "X-Workspace-Id": number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeEntryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_time_entry_api_v1_time_entries__id__get: {
        parameters: {
            query?: never;
            header: {
                "X-Workspace-Id": number;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeEntryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_time_entry_api_v1_time_entries__id__put: {
        parameters: {
            query?: never;
            header: {
                "X-Workspace-Id": number;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimeEntryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeEntryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_time_entry_api_v1_time_entries__id__delete: {
        parameters: {
            query?: never;
            header: {
                "X-Workspace-Id": number;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workspaces_api_v1_workspaces_get: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Page size */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_WorkspaceRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_workspace_api_v1_workspaces_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_workspace_api_v1_workspaces__delete: {
        parameters: {
            query?: never;
            header: {
                "X-Workspace-Id": number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workspace_members_api_v1_workspaces_members_get: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Page size */
                size?: number;
            };
            header: {
                "X-Workspace-Id": number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_WorkspaceMemberRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_workspace_member_api_v1_workspaces_members__member_id__put: {
        parameters: {
            query?: never;
            header: {
                "X-Workspace-Id": number;
            };
            path: {
                member_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceMemberUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceMemberRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_workspace_member_api_v1_workspaces_members__member_id__delete: {
        parameters: {
            query?: never;
            header: {
                "X-Workspace-Id": number;
            };
            path: {
                member_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    leave_workspace_api_v1_workspaces_members_me_delete: {
        parameters: {
            query?: never;
            header: {
                "X-Workspace-Id": number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_workspace_invitations_api_v1_workspaces_invitations_get: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Page size */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_WorkspaceInvitationRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_invitation_api_v1_workspaces_invitations_post: {
        parameters: {
            query?: never;
            header: {
                "X-Workspace-Id": number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceInvitationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceInvitationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_invitation_api_v1_workspaces_invitations_accept__invitation_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invitation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_invitation_api_v1_workspaces_invitations_revoke__invitation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invitation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_live_report_api_v1_reports_live_get: {
        parameters: {
            query: {
                period_start: string;
                period_end: string;
                client_ids?: number[] | null;
                project_ids?: number[] | null;
                billable?: boolean | null;
            };
            header: {
                "X-Workspace-Id": number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeEntryRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_static_reports_api_v1_reports__get: {
        parameters: {
            query?: {
                query?: string | null;
                /** @description Page number */
                page?: number;
                /** @description Page size */
                size?: number;
            };
            header: {
                "X-Workspace-Id": number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ReportRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_live_report_api_v1_reports__post: {
        parameters: {
            query?: never;
            header: {
                "X-Workspace-Id": number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReport"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_single_static_report_api_v1_reports__id__get: {
        parameters: {
            query?: never;
            header: {
                "X-Workspace-Id": number;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_static_report_api_v1_reports__id__delete: {
        parameters: {
            query?: never;
            header: {
                "X-Workspace-Id": number;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    share_static_report_api_v1_reports__id__share_put: {
        parameters: {
            query?: never;
            header: {
                "X-Workspace-Id": number;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_notifications_api_v1_notifications__get: {
        parameters: {
            query?: {
                unread?: boolean;
                /** @description Page number */
                page?: number;
                /** @description Page size */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_NotificationRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_notification_api_v1_notifications__id__read_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
