"""enrich project

Revision ID: 00d63d08701a
Revises: f58453e5c611
Create Date: 2026-08-05 09:42:07.962249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00d63d08701a'
down_revision: Union[str, Sequence[str], None] = 'f58453e5c611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('description', sa.String(length=128), nullable=True))
    op.add_column('projects', sa.Column('start_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('end_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'end_time')
    op.drop_column('projects', 'start_time')
    op.drop_column('projects', 'description')
    # ### end Alembic commands ###
