"""cascade deletion for time_entries<->project

Revision ID: 137137389a02
Revises: 00d63d08701a
Create Date: 2026-08-05 11:11:08.207951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '137137389a02'
down_revision: Union[str, Sequence[str], None] = '00d63d08701a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('time_entries_project_id_fkey'), 'time_entries', type_='foreignkey')
    op.create_foreign_key(None, 'time_entries', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'time_entries', type_='foreignkey')
    op.create_foreign_key(op.f('time_entries_project_id_fkey'), 'time_entries', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
