"""add billing details

Revision ID: 46a610aee715
Revises: 7dea2c34f788
Create Date: 2026-08-14 20:32:37.018076

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46a610aee715"
down_revision: Union[str, Sequence[str], None] = "7dea2c34f788"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "clients",
        sa.Column(
            "hourly_rate",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
        ),
    )

    op.add_column(
        "clients",
        sa.Column(
            "currency",
            sa.String(length=3),
            nullable=False,
            server_default="CZK",
        ),
    )

    op.add_column(
        "time_entries",
        sa.Column(
            "billable",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )

    # Existing rows now have valid values.
    op.alter_column(
        "clients",
        "currency",
        server_default=None,
    )

    op.alter_column(
        "time_entries",
        "billable",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("time_entries", "billable")
    op.drop_column("clients", "currency")
    op.drop_column("clients", "hourly_rate")
    # ### end Alembic commands ###
