"""fix naming in refrehs_tokens

Revision ID: 4c2b1cd56a9b
Revises: 729bb8bdd3b6
Create Date: 2026-08-05 11:48:57.407702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c2b1cd56a9b'
down_revision: Union[str, Sequence[str], None] = '729bb8bdd3b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('token_hash', sa.String(length=255), nullable=False))
    op.drop_constraint(op.f('refresh_tokens_tokenHash_key'), 'refresh_tokens', type_='unique')
    op.create_unique_constraint(None, 'refresh_tokens', ['token_hash'])
    op.drop_column('refresh_tokens', 'tokenHash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('tokenHash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'refresh_tokens', type_='unique')
    op.create_unique_constraint(op.f('refresh_tokens_tokenHash_key'), 'refresh_tokens', ['tokenHash'], postgresql_nulls_not_distinct=False)
    op.drop_column('refresh_tokens', 'token_hash')
    # ### end Alembic commands ###
