"""empty message

Revision ID: 910b813dfc79
Revises: 1cd41974af61
Create Date: 2026-08-22 07:57:39.504028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '910b813dfc79'
down_revision: Union[str, Sequence[str], None] = '1cd41974af61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspace_members', 'role',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('owner', 'admin', 'member', name='workspacerole'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspace_members', 'role',
               existing_type=sa.Enum('owner', 'admin', 'member', name='workspacerole'),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###
