"""add workspaces

Revision ID: c6c67eee47fb
Revises: 05083d28a649
Create Date: 2026-08-13 12:42:19.339098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6c67eee47fb'
down_revision: Union[str, Sequence[str], None] = '05083d28a649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name')
    )
    op.drop_constraint(op.f('projects_user_id_fkey'), 'projects', type_='foreignkey')
    op.drop_column('projects', 'user_id')
    op.add_column('time_entries', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('time_entries_client_id_fkey'), 'time_entries', type_='foreignkey')
    op.drop_constraint(op.f('time_entries_project_id_fkey'), 'time_entries', type_='foreignkey')
    op.create_foreign_key(None, 'time_entries', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'time_entries', 'clients', ['client_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'time_entries', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'time_entries', type_='foreignkey')
    op.drop_constraint(None, 'time_entries', type_='foreignkey')
    op.drop_constraint(None, 'time_entries', type_='foreignkey')
    op.create_foreign_key(op.f('time_entries_project_id_fkey'), 'time_entries', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('time_entries_client_id_fkey'), 'time_entries', 'clients', ['client_id'], ['id'])
    op.drop_column('time_entries', 'workspace_id')
    op.add_column('projects', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('projects_user_id_fkey'), 'projects', 'users', ['user_id'], ['id'])
    op.drop_table('workspaces')
    # ### end Alembic commands ###
