"""make fiels optional

Revision ID: e809fe9d5636
Revises: 22dfe1cc1fbd
Create Date: 2026-07-27 18:23:54.644125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e809fe9d5636'
down_revision: Union[str, Sequence[str], None] = '22dfe1cc1fbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('time_entries', 'description',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('time_entries', 'description',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('projects', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
