/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppClientsIndexRouteImport } from './routes/app/clients/index'
import { Route as AppClientsIdRouteImport } from './routes/app/clients/$id'
import { Route as AppClientsNewRouteImport } from './routes/app/clients/new'
import { Route as AppProjectsIndexRouteImport } from './routes/app/projects/index'
import { Route as AppProjectsIdRouteImport } from './routes/app/projects/$id'
import { Route as AppProjectsNewRouteImport } from './routes/app/projects/new'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClientsIdRoute = AppClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClientsNewRoute = AppClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsNewRoute = AppProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/app/': typeof AppIndexRoute
  '/app/clients/$id': typeof AppClientsIdRoute
  '/app/clients/new': typeof AppClientsNewRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
  '/app/projects/new': typeof AppProjectsNewRoute
  '/app/clients/': typeof AppClientsIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/': typeof PublicIndexRoute
  '/app': typeof AppIndexRoute
  '/app/clients/$id': typeof AppClientsIdRoute
  '/app/clients/new': typeof AppClientsNewRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
  '/app/projects/new': typeof AppProjectsNewRoute
  '/app/clients': typeof AppClientsIndexRoute
  '/app/projects': typeof AppProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_public/': typeof PublicIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/clients/$id': typeof AppClientsIdRoute
  '/app/clients/new': typeof AppClientsNewRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
  '/app/projects/new': typeof AppProjectsNewRoute
  '/app/clients/': typeof AppClientsIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/'
    | '/app/clients/$id'
    | '/app/clients/new'
    | '/app/projects/$id'
    | '/app/projects/new'
    | '/app/clients/'
    | '/app/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/'
    | '/app'
    | '/app/clients/$id'
    | '/app/clients/new'
    | '/app/projects/$id'
    | '/app/projects/new'
    | '/app/clients'
    | '/app/projects'
  id:
    | '__root__'
    | '/_public'
    | '/app'
    | '/_public/login'
    | '/_public/register'
    | '/_public/'
    | '/app/'
    | '/app/clients/$id'
    | '/app/clients/new'
    | '/app/projects/$id'
    | '/app/projects/new'
    | '/app/clients/'
    | '/app/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/clients/': {
      id: '/app/clients/'
      path: '/clients'
      fullPath: '/app/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/clients/$id': {
      id: '/app/clients/$id'
      path: '/clients/$id'
      fullPath: '/app/clients/$id'
      preLoaderRoute: typeof AppClientsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/clients/new': {
      id: '/app/clients/new'
      path: '/clients/new'
      fullPath: '/app/clients/new'
      preLoaderRoute: typeof AppClientsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/projects/': {
      id: '/app/projects/'
      path: '/projects'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/projects/$id': {
      id: '/app/projects/$id'
      path: '/projects/$id'
      fullPath: '/app/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/projects/new': {
      id: '/app/projects/new'
      path: '/projects/new'
      fullPath: '/app/projects/new'
      preLoaderRoute: typeof AppProjectsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppClientsIdRoute: typeof AppClientsIdRoute
  AppClientsNewRoute: typeof AppClientsNewRoute
  AppProjectsIdRoute: typeof AppProjectsIdRoute
  AppProjectsNewRoute: typeof AppProjectsNewRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppClientsIdRoute: AppClientsIdRoute,
  AppClientsNewRoute: AppClientsNewRoute,
  AppProjectsIdRoute: AppProjectsIdRoute,
  AppProjectsNewRoute: AppProjectsNewRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
