"""empty message

Revision ID: 325cb9b65602
Revises: 7efb574aae0a
Create Date: 2026-08-30 15:11:03.756861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '325cb9b65602'
down_revision: Union[str, Sequence[str], None] = '7efb574aae0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_issued_invoice_workspace_document_number', 'issued_invoices', ['workspace_id', 'document_number'])
    op.create_unique_constraint(None, 'issued_invoices', ['workspace_id'])
    op.drop_constraint(op.f('issued_invoices_workspace_id_fkey'), 'issued_invoices', type_='foreignkey')
    op.create_foreign_key(None, 'issued_invoices', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issued_invoices', type_='foreignkey')
    op.create_foreign_key(op.f('issued_invoices_workspace_id_fkey'), 'issued_invoices', 'workspaces', ['workspace_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'issued_invoices', type_='unique')
    op.drop_constraint('uq_issued_invoice_workspace_document_number', 'issued_invoices', type_='unique')
    # ### end Alembic commands ###
