"""proper cascade

Revision ID: 7dea2c34f788
Revises: 891845334d33
Create Date: 2026-08-13 13:14:59.984535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dea2c34f788'
down_revision: Union[str, Sequence[str], None] = '891845334d33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'clients', ['workspace_id', 'name'])
    op.drop_constraint(op.f('clients_user_id_fkey'), 'clients', type_='foreignkey')
    op.create_foreign_key(None, 'clients', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_column('clients', 'user_id')
    op.alter_column('projects', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('projects_client_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_client_id_fkey'), 'projects', 'clients', ['client_id'], ['id'])
    op.alter_column('projects', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('clients', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.create_foreign_key(op.f('clients_user_id_fkey'), 'clients', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_column('clients', 'workspace_id')
    # ### end Alembic commands ###
