"""add invoices

Revision ID: 7efb574aae0a
Revises: 382dd921d45d
Create Date: 2026-08-30 13:50:00.215718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7efb574aae0a'
down_revision: Union[str, Sequence[str], None] = '382dd921d45d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('number_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('counter', sa.Integer(), nullable=False),
    sa.Column('format_template', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issued_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('number_series_id', sa.Integer(), nullable=False),
    sa.Column('document_number', sa.String(length=50), nullable=False),
    sa.Column('date_issue', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_taxing', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_maturity', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['number_series_id'], ['number_series.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issued_invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['issued_invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('clients', sa.Column('is_company', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('clients', sa.Column('street', sa.String(length=255), nullable=True))
    op.add_column('clients', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('postal_code', sa.String(length=10), nullable=True))
    op.add_column('clients', sa.Column('country', sa.String(length=2), nullable=True))
    op.add_column('clients', sa.Column('ico', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('dic', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('vat_payer', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('clients', sa.Column('bank_account', sa.String(length=34), nullable=True))
    op.add_column('clients', sa.Column('iban', sa.String(length=34), nullable=True))
    op.add_column('clients', sa.Column('discount_percentage', sa.Numeric(precision=4, scale=2), nullable=True))
    op.alter_column('clients', 'name',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_column('clients', 'discount_percentage')
    op.drop_column('clients', 'iban')
    op.drop_column('clients', 'bank_account')
    op.drop_column('clients', 'vat_payer')
    op.drop_column('clients', 'dic')
    op.drop_column('clients', 'ico')
    op.drop_column('clients', 'country')
    op.drop_column('clients', 'postal_code')
    op.drop_column('clients', 'city')
    op.drop_column('clients', 'street')
    op.drop_column('clients', 'is_company')
    op.drop_table('issued_invoice_items')
    op.drop_table('issued_invoices')
    op.drop_table('number_series')
    # ### end Alembic commands ###
