"""add metadata to user account

Revision ID: a7fbeeb57397
Revises: 325cb9b65602
Create Date: 2026-09-01 10:41:44.510210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7fbeeb57397'
down_revision: Union[str, Sequence[str], None] = '325cb9b65602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('locale', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.String(length=64), nullable=True))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=320),
               existing_nullable=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'locale')
    op.drop_column('users', 'last_login_at')
    # ### end Alembic commands ###
