"""update reports

Revision ID: acc7b1b03ff0
Revises: eaa52cfe9f4b
Create Date: 2026-08-17 18:02:57.923485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acc7b1b03ff0'
down_revision: Union[str, Sequence[str], None] = 'eaa52cfe9f4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reports', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'project_id')
    # ### end Alembic commands ###
