"""add uuid to flag a shareable report

Revision ID: e69cd6a747e1
Revises: fe5cf7225af8
Create Date: 2026-08-19 21:48:15.680179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e69cd6a747e1'
down_revision: Union[str, Sequence[str], None] = 'fe5cf7225af8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('uuid', sa.Uuid(), nullable=True))
    op.create_unique_constraint(None, 'reports', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='unique')
    op.drop_column('reports', 'uuid')
    # ### end Alembic commands ###
