"""add reports to workspace

Revision ID: eaa52cfe9f4b
Revises: 8cde711c3a06
Create Date: 2026-08-15 12:56:20.383183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaa52cfe9f4b'
down_revision: Union[str, Sequence[str], None] = '8cde711c3a06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'reports', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'workspace_id')
    # ### end Alembic commands ###
