"""empty message

Revision ID: f3464bc85e64
Revises: 9709e6e7aba0
Create Date: 2026-08-27 07:41:36.950733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3464bc85e64'
down_revision: Union[str, Sequence[str], None] = '9709e6e7aba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('reports_client_id_fkey'), 'reports', type_='foreignkey')
    op.drop_constraint(op.f('reports_project_id_fkey'), 'reports', type_='foreignkey')
    op.drop_column('reports', 'client_id')
    op.drop_column('reports', 'project_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('reports_project_id_fkey'), 'reports', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('reports_client_id_fkey'), 'reports', 'clients', ['client_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
