"""add client-time_entries

Revision ID: f58453e5c611
Revises: 0f0cf5c0c7be
Create Date: 2026-08-02 20:38:57.572886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f58453e5c611'
down_revision: Union[str, Sequence[str], None] = '0f0cf5c0c7be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_entries', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'time_entries', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'time_entries', type_='foreignkey')
    op.drop_column('time_entries', 'client_id')
    # ### end Alembic commands ###
